<?php

function print_page($title, $context, $heading, $content, $subtabs = array())
{
        // hnave values are as follow
        //  - the URL path (relative if possible)
        //  - the label as used in tabs and the navigation
        //  - (optional) the id of the tab it is under, this is for subsections
	$hnav = array( "summary" => array("/", "Home"),
			"home" => array("/", "Home"),
			"download" => array("/download/", "Download"),
			"discover" => array("/discover/", "Discover"),
			"comingsoon" => array("/discover/comingsoon/", 
                                              "Coming Soon", "discover"),
			"planet" => array("http://planet.go-oo.org/", "Planet"),
			"developers" => array("/developers/", "Developers"),
			"users" => array("/users/", "Users"),
			"mgp" => array("/users/mgp", "Magicpoint"),
			"mailarchive" => array("/developers/mailarchive", 
                                               "Mail archive", "developers"),
			"about" => array("/about/", "About") 
			);
        // tabs state. the all have the "container" value
	// and the current one MUST have the "selected" value
	// this is all dependent on ths CSS used.
	$tabs = array ( "summary" => "container", 
	       	       	 "download" => "container", 
	       		 "discover" => "container", 
	       		 "planet" => "container", 
			 "developers" => "container",
	       		 "about" => "container" ); 
	
	$id = "summary";
	foreach ($context as $c) {
		if (array_key_exists ($c, $tabs)) {
			$id = $c;
			break;
		}
	}
	// the current tab is selected
	$tabs[$id] = "selected";
?>
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <title><?php print $heading; ?></title>
        <style type="text/css">
            @import url(/css/blueprint/print.css) print;
            @import url(/css/blueprint/screen.css) screen;
            @import url(/css/tabs.css);
            @import url(/css/style.css);
        </style>
<?php
//        <script type="text/javascript" src="/js/jquery.js"></script>
//        <script type="text/javascript" src="/js/jquery.tabs.pack.js"></script>
?>
        <script type="text/javascript" src="/js/jquery.history_remote.pack.js"></script>
        <script type="text/javascript" src="/js/interface.js"></script>
        <script type="text/javascript" src="/js/script.js"></script>
    </head>
    <body>
<!-- DO NOT EDIT ! the html is generated by PHP. Edit the PHP instead -->
        <div id="wrap">

            <div id="header">
                <h1><a href="/">Go-OO</a></h1>
            </div>
            <div id="container">
                <ul id="nav">
<?php
			foreach($tabs as $key => $value)
			{
				$link = $hnav[$key];
				echo "<li class=\"tabs-$value\"><a href=\"$link[0]\">$link[1]</a></li>\n";

			}
		?>
                </ul>
                <div id="tagline">
                        <a href="http://www.go-oo.org">Better, Faster, Freer</a>
                </div>
<?php
		if (count ($subtabs) > 0) {
			echo "<ul id=\"hnav\">\n";

			foreach($subtabs as $key => $value) {
				echo "<li><a href=\"$value\">$key</a></li>\n";
			}
			echo "</ul>\n";
		}
?>

                <div class="container">
                    <div id="splash">
                        <h2><?php print $heading; ?></h2>
			<?php print $content . "\n"; ?>
                    </div>
                </div>

            </div>

            <div id="sidebar">
                <div class="text">
                    open office<br />
                    development
                </div>
            </div>

        </div>
    </body>
</html>

<?php
}
?>
