<?php
require("../template.php");

print_page("Go-OO! - Discover", "discover",
   "Discover OpenOffice.org",

   "<p>Here you'll discover what Go-oo has to offer in addition to the ".
   "regular build of OpenOffice.org</p>\n" .

   "<table>".
   "<tr>".

   "<td>".
   "<h4>VBA support</h4>".
   "<p>Go-oo provide VBA macros support for OpenOffice.org (<a href=\"excel-vba.xls\">download</a>)</p>".
   "<p><a href=\"go-excel-vba.png\">".
   "<img src=\"go-excel-vba-thumb.png\"/></a></p>".
   "</td>".

   "<td>".
   "<h4>Startup performance</h4>".
   "<p>Go-oo starts faster: (go-oo 2.1 vs. Sun/OO.o 2.3)</p>".
   "<img src=\"startup.png\"/></a>".
   "</td>".

   "</tr>".
   "<tr>".

   "<td colspan=\"2\">".
   "<h4>GStreamer integration</h4>".
   "<p>Go-oo supports multimedia content into your document using the ".
   "gstreamer multimedia framework".
   "</p>".
   "<table>".
   "<tr><th>Before</th>".
   "<th>After</th></tr>".
   "<tr><td><a href=\"oo-gstreamer.png\"><img src=\"oo-gstreamer-thumb.png\" /></a></td>\n".
   "<td><a href=\"go-gstreamer.png\"><img src=\"go-gstreamer-thumb.png\"".
   "/></a></td></tr>\n".
   "</table>".
   "</td>".

   "</tr>".
   "<tr>".

   "<td>".
   "<h4>MS-Works import</h4>".
   "<p>Go-oo supports MS-Works files.</p>".
   "<a href=\"go-msworks.png\"><img src=\"go-msworks-thumb.png\" /></a>".
   "</td>".

   "<td>".
   "<h4>WordPerfect Graphics import</h4>".
   "<p>Go-oo imports graphics in the WPG format coming from WordPerfect".
   "which supplement the WordPerfect importer also available in Go-oo.</p>".
   "<a href=\"go-wpg-support.png\"><img src=\"go-wpg-support-thumb.png\" /></a>".
   "</td>".

   "</tr>".
   "</table>".

//   "<h4>Office OpenXML import</h4>".
//   "<p>Go-oo integrates the work in progress made with importing documents in the Microsoft ".
//   "Office OpenXML formats that are generated by Microsoft Office 2007.</p>".
//   "<table>" .
//   "<tr>".
//   "<th>docx</th><th>xlsx</th><th>xlsx</th></tr>".
//   "<tr><td><a href=\"go-docx-sample.png\"><img src=\"go-docx-sample-thumb.png\"/></a></td>".
//   "<td><a href=\"go-xslx-sample1.png\"><img src=\"go-xslx-sample1-thumb.png\"/></a></td>".
//   "<td><a href=\"go-xslx-sample2.png\"><img src=\"go-xslx-sample2-thumb.png\"/></a></td></tr>".
//   "</table>".

   ""
   );

?>

